spring:
  cloud:
    config:
      server:
        native: # 使用本地配置文件
          search-locations: classpath:/configurations
  profiles: # 使用本地文件系统的配置文件时，profile 指定native
    active: native
  security:
    user:
      password: ${CONFIG_PASS:dev}



management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: ${PORT:8888}

